language: node_js
node_js:
- node
branches:
  only:
  - "/^\\d{1}\\.\\d{1,2}.\\d{1,2}$/"
notifications:
  email:
    recipients:
    - chaos@xuyuanxiang.cn
    on_success: never
    on_failure: always
before_deploy: npm run release
deploy:
  provider: npm
  email: chaos@xuyuanxiang.cn
  api_key:
    secure: JJj03thAcD47h7pD7SkyBTd7E5+SEIE2U5O1IOWVajNPf7uNVTFvIJvassUpXkPQgvLahu4fyFq1galsZTxVyA6aah+uGB2qulYGJNYn3/gQr8JddUsykHt8zxmLjDEXZZl3JPDQb/mfeqAzyixa5gVZpm3khHfGnpw2Fe9K1cFS8/BKoFE+6sEEBRf97wVw2tSV55b93P0A5R62bciMv+wAaVL80UQnovV5gSvc14KoMhTC2cLp9lrgfC8Y8YQfdMWP6hCDVrfn2LxutZCEFSrIJb2v6PyLq+81toZ9q0lhLDLhxaSL2XqmNKLpZzOOe560Il3WwE10pHitu4yr02j47qX+ECQ29vTPi7L3zkdy8DyBcm/82bldaH6nS5xefPZwz6avALJoqex1umayTimB3zoDZCM5RRi9l5tlNnlf0j/2yasa3Tb+Az6KCpZl/7tTT3WFlE4iUB93law9lQ8oOTvmoQlMsNCkWB8lOpAlvoKGvQkZH6pwdsqQ6TaeFrlDKYr5JhEz6kbxpxz22ZX3C/N7BpygFOobr03oR2+ABIipJ9WV/E+O8Brpz62fX6zi9Er77VnlxEfIJ3/0qx56gxYJK3hL+CP6LRqNBrTBEp3uCBqfer7aTwaDdyhO54VeLgKQQFtmBnjyUyF2TO0P/MGaljfXc+Czih5FJXs=
  on:
    tags: true
    repo: xuyuanxiang/heirloom-core
